---
abstract: 'Framework to import row-based (spreadsheet-, csv-) files into a database'
author:
  - 'Kaare Rasmussen <kaare@cpan.org>'
build_requires:
  DBD::SQLite: '0'
  DBIx::Class::Core: '0'
  DBIx::Class::Schema: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0'
  base: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Importer
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Data::Importer:
    file: lib/Data/Importer.pm
    version: '0.004'
  Data::Importer::Iterator:
    file: lib/Data/Importer/Iterator.pm
    version: '0.004'
  Data::Importer::Iterator::Csv:
    file: lib/Data/Importer/Iterator/Csv.pm
    version: '0.004'
  Data::Importer::Iterator::Ods:
    file: lib/Data/Importer/Iterator/Ods.pm
    version: '0.004'
  Data::Importer::Iterator::Xls:
    file: lib/Data/Importer/Iterator/Xls.pm
    version: '0.004'
requires:
  DateTime: '0'
  DateTime::Format::Pg: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Traits: '0'
  Spreadsheet::ParseExcel: '0'
  Spreadsheet::Read: '0'
  Spreadsheet::ReadSXC: '0'
  Text::CSV: '0'
  namespace::autoclean: '0'
  perl: '5.010'
resources:
  homepage: https://github.com/kaare/Data-Importer
  repository: https://github.com/kaare/Data-Importer.git
version: '0.004'
